# Generated by Django 5.1.6 on 2025-02-20 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EntryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='occupancy.entrance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('entrance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exits', to='occupancy.entrance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
